baseurl = "https://www.monkeypatching.com/"
languageCode = "en-us"
title = "Monkey Patching"
theme = "purehugo"
Paginate = 10
disqusShortname = "monkeypatching"

[params]
    twitterName = "pawelkowalak"
    githubName = "pawelkowalak"
    description = "Pawel Kowalak"
    google_analytics = "UA-80579269-1"